### ISSUE TITLE
Historical Date Pull

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#26]
The historical data is off by one to two days depending on the plots.  I believe it has to do with how/when we're pulling information from the source website.  The csv's in the data_files folder have the most current info being 4/26 and the csv at the actual source has current info up to 4/27.

**Comment by galarcon0308** [comment]
Changed case and death to the old way of downloading, by just pulling straight from the github of the sources. Since the global file only runs once (when Shiny server starts), this shouldn't be a huge time consumption since when users connect to the website only the server function runs. 

Also the daily chart was off by a day, that has been fixed.

**Comment by ajkeith** [comment]
@ltcarendt sir, please let us know if this causes any problems on the VAULT instance

**Comment by ltcarendt** [comment]
@ajkeith Yes, caused some problems; back to old behavior of several 502 server errors and requiring multiple reloads before dashboard successfully loads to make the data "current".
The data loads really slow on the VAULT platform.
I'm gonna try to create a cron job on the VAULT platform to run the global.R script at 0600 and 1800 every day and see if that prevents the 502 error.

**Comment by ltcarendt** [comment]
No joy; pre-running global.R has no effect; still encounters multiple 502 errors and require multiple re-loads before successfully loading the dashboard
